# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IronSource Mediation Demo - ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IronSource Mediation Demo - ObjC
  pod 'IronSourceSDK','7.3.0.0'
end
